#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [ "xrandr | grep -sw "connected" | wc -l" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 2p) -d I II III IV V VI VIII
  bspc monitor $(bspc query -M | sed -n 1p) -d IX X
else
  bpsc monitor -d I II III IV V VI VII VIII IX X
fi

bspc monitor DP-2 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI-0 -d 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#AutoStart
picom &
feh --bg-center $HOME/Pictures/Wallpapers/$(ls $HOME/Pictures/Wallpapers/ | shuf -n 1)
$HOME/.config/polybar/launch.sh
unclutter &
